apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: pg-root-cert
        defaultMode: 0600
  containers:
  - name: ubuntu-container
    image: ubuntu:latest
    command:
      - bash
      - -c
    args:
      - |
        apt-get update
        apt-get install postgresql-client -y
        apt-get install wget -y
        sleep infinity
    envFrom:
      - configMapRef:
          name: kube-root-ca.crt
      - secretRef:
          name: postgres
    volumeMounts:
      - name: secret-volume
        readOnly: true
        mountPath: "/root/.postgresql"
