apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
  labels:
    app.kubernetes.io/name: django-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: django-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: django-app
    spec:
      containers:
        - name: django-app
          image: django_app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              name: django-app-port
          envFrom:
            - configMapRef:
                name: app-configmap
            - secretRef:
                name: app-secret
